### ISSUE TITLE
Could you add hide arrows option?

### ISSUE THREAD

**Issue by 7hat3eird0ne** [capeling/Startpos-Switcher#1]
Sometimes I accidentely click the arrows on pc with my cursor which is invisible, so I thought it would be nice to be able to remove the arrows, this way mobile users can leave them on so they can use the mod, but pc users could play without any problems with accidentely switching sp

also you could maybe make the e and q buttons keybindable using keybinds mod or how is it called, but i dont rlly know how hard it is so to add that

srry if I am annoying I am new to the github thingies like this

**Comment by capeling** [comment]
hide arrows added in v1.0.3, custom keybinds is a maybe
