### ISSUE TITLE
[suggestion] Hide Label upon Level Enter

### ISSUE THREAD

**Issue by Aktimoose** [capeling/Startpos-Switcher#2]
With opacity set to 0, I'd like the option for the label to be hidden at all times aside from only when I am changing start positions. This is useful for levels in which I already know there are start positions (such as my own copyables) so I can have a cleaner experience for when I'm not utilising them.

Don't want this every time I open Dash
![20240629100816_1](https://github.com/Capeling/Startpos-Switcher/assets/44620677/6ce78075-3280-47dd-8f06-82ff417deb88)

**Comment by capeling** [comment]
added as a setting in v1.0.3
