### ISSUE TITLE
Bug with keyboard

### ISSUE THREAD

**Issue by ViatronGMD** [capeling/Startpos-Switcher#4]
Bit of a strange bug I know but it's really annoying for someone who uses a USB keyboard with my android phone so I can use Z and X for practice mode checkpoints, easier editor, e.t.c.

I've checked all the other mods that I'm using and it's definitely your one, and you see whenever I press a key while playing a level the game crashes, and I mean any key, even the Q and E ones which are supposed to change the startpos

If you need me to become a test subject then I'm perfectly fine with that, but please solve the issue asap 🙏

**Comment by capeling** [comment]
are you sure you disabled every mod?

**Comment by ViatronGMD** [comment]
100%, this problem only occurs with startPosSwitcher

**Comment by capeling** [comment]
well tbh i dont see how i can fix that, it could be a hook screwing up but that wouldnt be my problem then, that would be tuliphook

**Comment by capeling** [comment]
should be fixed in 1.0.4
